      integer istrn,istupd,ibelyt,miter,ipstpd,intsts,nodsts,intstn,
     1        nodstn,jstrn,nddet,nsout01,nsout02,nsout03,nsout04,
     2        nsout05,nsout06,mporlk,lporlk,istrn_t,istrn_p
      real wrpang
      common/shlopt/istrn,istupd,ibelyt,miter,wrpang,
     1 ipstpd,intsts,nodsts,intstn,nodstn,jstrn,nddet,nsout01,
     2 nsout02,nsout03,nsout04,nsout05,nsout06,mporlk,lporlk,
     3 istrn_t,istrn_p
